# define some variables
# tyla = "#BC29FF"

[window]
dimensions.columns = 120 
dimensions.lines = 30
opacity = 0.4
blur = true

[font]
normal = {family = "Jetbrains Mono", style = "Regular"}
size = 16.0

[cursor]
style = { shape = "Underline", blinking = "On"}

[colors]
cursor = { text = "#BC29FF", cursor = "#BC29FF" }

[general]
working_directory = "/home/ahbr/"
